# Generated by Django 5.0.2 on 2024-02-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('clname', models.CharField(max_length=30)),
                ('cadd', models.TextField(max_length=200)),
                ('cphone', models.IntegerField()),
                ('csalary', models.FloatField()),
            ],
        ),
    ]
